export PAGER=less

export EDITOR=nvim
export VISUAL=nvim
export MANPAGER="nvim +Man!"

source <(fzf --zsh)

alias ls='eza --color=auto'
alias ll='eza -alhF --color=auto --group-directories-first'
alias cat='bat'
