export PAGER=less

export EDITOR=nvim
export VISUAL=nvim
export MANPAGER="nvim +Man!"

source <(fzf --zsh)

# alias ls='eza --color=auto'
alias ll='eza -alhF --color=auto --group-directories-first'
alias cat='bat'

# export FONTCONFIG_FILE=$(nix-build -E 'let pkgs = import <nixpkgs> { }; in pkgs.makeFontsConf { fontDirectories = [ pkgs.freefont_ttf ]; }')

# >>> juliaup initialize >>>

# !! Contents within this block are managed by juliaup !!

path=("$HOME/.juliaup/bin" $path)
export PATH

# <<< juliaup initialize <<<
